version: 1.0.{build}
  build_cloud: #这里选择构建的类型  
  - Docker  
  image: net6.0 # 这里选择构建的镜像  
  configuration: Release
  
build:
  project: HelloWorldWebApp.csproj
  verbosity: minimal

test_script:
- ps: dotnet test